apiVersion: v1
kind: PersistentVolume
metadata:
  name: vvpv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /backu
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vvpvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

